### PR TITLE
fix(migration): fix migration when another model with a different id exists

### LINKED ISSUE #159: Migration fails when another model with a different id exists
The following change to the migrate test illustrates the issue.
With the additional model it throws an error:
```
Impossible to migrate the table 1_2_generate_my_primary_key because the table 1_1_generate_my_primary_key has data
```

```diff
diff --git a/tests/migrate/only_primary_key.rs b/tests/migrate/only_primary_key.rs
index 36695d4..33c83b6 100644
--- a/tests/migrate/only_primary_key.rs
+++ b/tests/migrate/only_primary_key.rs
@@ -51,13 +51,27 @@ impl ItemV2 {
     }
 }
 
+#[derive(Serialize, Deserialize, Eq, PartialEq, Debug, Clone)]
+#[native_model(id = 2, version = 1)]
+#[native_db]
+struct Item2 {
+    #[primary_key]
+    id: u32,
+}
+
 #[test]
 fn test_migrate() {
     let tf = TmpFs::new().unwrap();
     let mut builder = DatabaseBuilder::new();
     builder.define::<ItemV1>().unwrap();
+    builder.define::<Item2>().unwrap();
     let db = builder.create(tf.path("test").as_std_path()).unwrap();
 
+    let item_2 = Item2 { id: 1 };
+    let rw_txn = db.rw_transaction().unwrap();
+    rw_txn.insert(item_2).unwrap();
+    rw_txn.commit().unwrap();
+
     let item = ItemV1 {
         id: 1,
         name: "test".to_string(),
@@ -83,6 +97,7 @@ fn test_migrate() {
     let mut builder = DatabaseBuilder::new();
     builder.define::<ItemV1>().unwrap();
     builder.define::<ItemV2>().unwrap();
+    builder.define::<Item2>().unwrap();
     let db = builder.create(tf.path("test").as_std_path()).unwrap();
 
     let rw = db.rw_transaction().unwrap();
 ```

### PR DESCRIPTION
**Pull request by croissong**
fixes #159

### CODE REVIEW

**Comment by vincent-herlemont** [comment]
The CI failed due to a token issue, audit in progress here: https://github.com/vincent-herlemont/native_db/pull/161

**Comment by vincent-herlemont** [comment]
The [CI problem](https://github.com/vincent-herlemont/native_db/pull/160#issuecomment-2161187549) is not related to the code, so it's fine by me.

@croissong You can mark the issue as ready for review if you want me to merge it.

**Comment by croissong** [comment]
@vincent-herlemont thanks! 
I added two slightly unrelated commits just now:

- tried to improve the "Impossible to migrate the table ..." error message, because it confused me a bit when I encountered it, and I think it should be made clear that the issue is caused by *multiple* old tables with data. 
  I hope the error is at least a little bit better now :sweat_smile: 
  
- additional tests for migrating with multiple model versions, to make sure migrate logic still works after the change.
  But a just noticed that [test_migrate_v3](https://github.com/vincent-herlemont/native_db/blob/main/tests/migrate/with_secondary_keys.rs#L227) also covers multiple model versions...

**Comment by vincent-herlemont** [comment]
@croissong Thank you for improving the error message and adding the tests!

> But I just noticed that there's already [test_migrate_v3](https://github.com/vincent-herlemont/native_db/blob/main/tests/migrate/with_secondary_keys.rs#L227) which covers multiple model versions, so let me know if I should change/remove my tests

Yes, sorry for the naming of some of my tests like `test_migrate_v3`, which are not very descriptive. I should pay more attention to that.

This will be taken into account for Release 0.7.0. However, I am currently doing a major refactor, so it should be ready in one to two weeks.

**Pull request merged**
