### PR TITLE
Tidy up comment in database_builder.rs

### PR DESCRIPTION
**Pull request by extua**
Small edit I noticed in the docs.

### CODE REVIEW

**Comment by vincent-herlemont** [comment]
@extua thank you for this fix. Can you rename the commit following the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)?

```bash
docs: tidy up comment in database_builder.rs
```

**Comment by extua** [comment]
> @extua thank you for this fix! Can you rename the commit following the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)?
> 
> ```shell
> docs: tidy up comment in database_builder.rs
> ```

Thanks! I've changed that commit message now.

**Comment by vincent-herlemont** [comment]
@extua thanks, your changes have been accepted and will be included in this weekend's release :)

**Pull request merged**
